name: CI

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: [v1.12.10, v1.14.6, v1.16.2]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Create Kubernetes ${{ matrix.k8s }} cluster
      id: kind
      uses: engineerd/setup-kind@v0.1.0
      with:
        version: v0.6.0
        image: kindest/node:${{ matrix.k8s }}

    - name: Prepare cluster for testing
      run: |
        echo
        echo "waiting for nodes to be ready ..."
        kubectl wait --for=condition=Ready nodes --all --timeout=5m
        kubectl get nodes
        echo
        kubectl version
        echo
        kubectl apply -f https://github.com/kubevault/operator/raw/master/api/crds/catalog.kubevault.com_vaultserverversions.yaml --validate=false
